name: file-proxy-web-assets
version: 1.1.0.0
license: BSD3

dependencies:
- base >= 4.7 && < 5

extra-source-files:
- web/dist/*
- web/dist/assets/*

library:
  source-dirs: src
  exposed-modules:
  - FileProxy.WebAssets
  dependencies:
  - bytestring
  - file-embed
