name: file-proxy-web-assets
version: 1.2.0.0
license: BSD3

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
  - FileProxy.WebAssets
  dependencies:
  - bytestring
  - base64-bytestring
