name: file-proxy-web
version: 1.2.0.0
license: BSD3

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
  - FileProxy.Web
  - FileProxy.Web.Standalone
  - FileProxy.WebAssets
  dependencies:
  - file-proxy
  - bytestring
  - base64-bytestring
  - aeson
  - filepath
  - http-types
  - metro
  - metro-socket
  - metro-transport-crypto
  - optparse-applicative
  - periodic-client
  - periodic-common
  - scotty
  - time
  - warp
  - wai

executables:
  file-proxy-web:
    main:                file-proxy-web.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - file-proxy-web
  file-proxy-web-standalone:
    main:                file-proxy-web-standalone.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - file-proxy-web

tests:
  file-proxy-web-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - file-proxy-web
    - file-proxy
    - aeson
    - bytestring
    - directory
    - filepath
    - hspec
    - http-types
    - temporary
    - text
    - wai
    - wai-extra
